development:
  adapter: postgresql
  encoding: utf8
  database: treasure_trash_development
  pool: 5


test: &TEST
  adapter: postgresql
  encoding: utf8
  database: treasure_trash_test
  pool: 5


production:
  adapter: postgresql
  encoding: utf8
  database: treasure_trash_production
  pool: 5
